[package]
name = "rawl"
version = "0.1.0"
description = "Rawl - AI Fighting Game Betting Platform"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "rawl"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
solana-security-txt = "1.1.2"
